### ISSUE TITLE
Cannot import pytket: undefined symbol

### ISSUE THREAD

**Issue by we-taper** [CQCL/pytket#106]
The pypi installed pytket cannot be installed due to missing symbols:

Example notebook: <https://colab.research.google.com/drive/15-4oo9uYSmxbED8lr4lg_U35NYdIVV8u?usp=sharing>

**Comment by cqc-alec** [comment]
Thanks for the report. I will investigate this.

**Comment by cqc-alec** [comment]
This will be fixed in the coming 0.15.0 release.
