### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by KyleBooth** [CQCL/pytket#11]
When trying to install, get the following error:

`ERROR: Could not find a version that satisfies the requirement qiskit-aqua-chemistry~=0.4.0 (from pytket) (from versions: none)
ERROR: No matching distribution found for qiskit-aqua-chemistry~=0.4.0 (from pytket)
`

**Comment by cqc-alec** [comment]
It sounds as if you may be trying to install an older version of pytket. Could you please describe the steps leading to this error (and post the full output)? What is your OS and Python version?

**Comment by KyleBooth** [comment]
Hello there,

I was trying to use Python 3.5 when I encountered this issue. I updated to 3.6 and it installed fine. All is well!

**Comment by cqc-alec** [comment]
Great!
