### ISSUE TITLE
pytket not installing on any OS 

### ISSUE THREAD

**Issue by gravityshouldbenaut** [CQCL/pytket#13]
I tried installing pyket on Linux and Windows and have been getting this error. 
![image](https://user-images.githubusercontent.com/7109370/76156338-ea049900-60ad-11ea-8959-d2a32f9b9f8c.png)

**Comment by ss2165** [comment]
Pytket is unfortunately supported on Windows yet. For linux please could you tell me your distribution and python version. Most linux distributions should work, and you will need python versions 3.6 or 3.7.

**Comment by gravityshouldbenaut** [comment]
That makes a lot of sense! And nevermind, tried again using sudo pip3 install pytket and got it. Was using the Rigetti QMI
