### ISSUE TITLE
Error when trying to use ibmq_armonk

### ISSUE THREAD

**Issue by EliasCombarro** [CQCL/pytket#14]
Hi!

Trying to use the ibmq_armonk device as a backend raises an error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-cdd34c5081f7> in <module>()
----> 1 ibmq_b = IBMQBackend('ibmq_armonk')

1 frames
/usr/local/lib/python3.6/dist-packages/pytket/qiskit/qiskit_convert.py in process_device(backend)
    195     node_ers_dict = {}
    196     link_ers_dict = {tuple(pair): GateErrorContainer()
--> 197                      for pair in coupling_map}
    198 
    199     for index, qubit_info in enumerate(properties.qubits):

TypeError: 'NoneType' object is not iterable
---------------------------------------------------------------------------

It seems that a coupling_map is expected for any device, but ibmq_armonk has a single qubit and, hence, no coupling_map.

**Comment by ss2165** [comment]
Hi, thanks for letting us know! It looks there is a bug for single qubit backends. We will deal with it as part of bugfixes in the upcoming release.

**Comment by ss2165** [comment]
Fixed with release of pytket v0.5.2 and pytket-qiskit v0.4
