### ISSUE TITLE
Build of manual fails

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket#153]
Reason: pytket-quantinuum and pytket-pyquil have incompatible dependencies (pyjwt version requirement).

**Comment by cqc-melf** [comment]
Could be solved by adding qcs-api-client==0.21.0 to the requirements

**Comment by cqc-melf** [comment]
Temporarily fixed with https://github.com/CQCL/pytket/pull/158, need long term solution after pyquil is updated.

**Comment by cqc-melf** [comment]
Remove temp fixes https://github.com/CQCL/pytket/pull/163

**Comment by cqc-melf** [comment]
Solved
