### ISSUE TITLE
Remove workaround for docs build failure

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket#162]
With the release of pyquil 3.2.0 we should no longer need the qcs-api-client installation workaround introduced [here](https://github.com/CQCL/pytket/pull/161).

It is always possible that similar issues may arise in the future. This seems inevitable if we want to have a single python environment containing latest versions of multiple extensions. There is no guarantee this will be possible without conflicts. I don't know what the long-term solution is. Maybe make the manual pytket-only (no extensions), and have separate manuals for (some of) the extensions?

**Comment by cqc-melf** [comment]
I think the question we should think about is if we want to keep the examples and manual parts in one repo or if the extension specific examples should be moved over to the repos of the extensions. We for example already have examples in the pytket-quantinuum repo which are not here. I think the issue with that is that it is harder to keep them up to date if they are not at a central place for people to look up. Independently of that I think it would be the right step to move the extension specific examples over to the repos of the extensions (with workflows to check them, that would allow to check the remote functions of the examples, too. )

**Comment by cqc-melf** [comment]
And the right solution to the current situation is to go back to the workflow with one requirements file and remove the other temp fixes.

**Comment by cqc-melf** [comment]
From my understanding this is solved now
