### ISSUE TITLE
new version not available with pip

### ISSUE THREAD

**Issue by tbcdebug** [CQCL/pytket#17]
I noticed on [PyPi](https://pypi.org/project/pytket/), `0.5.4` is out. However, I upgraded `pip` to `20.1`, and used `pip install pytket==0.5.4`. It says 
```
ERROR: Could not find a version that satisfies the requirement pytket==0.5.4 (from versions: 0.0.1, 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.4.0, 0.4.1, 0.4.2)
ERROR: No matching distribution found for pytket==0.5.4
```

**Comment by cqc-alec** [comment]
Which version of Python are you using? Note that only 3.6, 3.7 and 3.8 are supported with pytket now.

**Comment by tbcdebug** [comment]
`Python 3.6.10 :: Anaconda, Inc.`

**Comment by cqc-alec** [comment]
OK, not that then. Operating system?

**Comment by tbcdebug** [comment]
MacOS 10.13.6 (17G12034)

**Comment by cqc-alec** [comment]
OK thanks. Our build scripts target MacOS 10.14 and above.
This is probably an unintentional compatibility break between versions 0.4 and 0.5.
As a workaround, other than upgrading to 10.14, you may be able to install by downloading https://files.pythonhosted.org/packages/2c/34/9e1c8aad4e65b47550267938540b46fab271091a22af5a906ebe94100356/pytket-0.5.4-cp36-cp36m-macosx_10_14_x86_64.whl and renaming the file (changing the "14" to a "13" before doing `pip install pytket-0.5.4-cp36-cp36m-macosx_10_13_x86_64.whl`.

**Comment by cqc-alec** [comment]
I have just checked with a colleague and in fact it was intentional, because we started making use of some C++17 features that would have required rewriting to bring the target back down. Apologies, this should have gone in the changelog. The above workaround may work nevertheless.

**Comment by tbcdebug** [comment]
OK. I got it running on a Linux machine.
