### ISSUE TITLE
Initialisation of qubits passed to the backends 

### ISSUE THREAD

**Issue by BoltzmannEntropy** [CQCL/pytket#177]
Hello,
In this simple circuit:
```
c = Circuit(2)
c.H(0).CX(0, 1)
backend = AerStateBackend()
c = backend.get_compiled_circuit(c)
handle = backend.process_circuit(c)
state = backend.get_result(handle).get_state()
print(state)

```
How do I set the initial qubit values? Let's say 0,1 to the first and second qubits respectively? 

Thanks,

**Comment by cqc-alec** [comment]
On the `AerStateBackend` (and most others), the qubits are automatically initialized to the all-zero state. To initialize to another computational basis state just add X gates as appropriate to the start of your circuit. In your example you'd need to prepend an X on the second qubit.

**Comment by BoltzmannEntropy** [comment]
I meant something such as: 

```
qc = QuantumCircuit(2)
initial_state = [0,1]  # Specify your initial state here
initial_state = [1/np.sqrt(2), 1/np.sqrt(2)]  # Define state |q_0>
initializer = Initialize(initial_state)  # create the gate
initializer.label = "init"  # give it a label (this is the step that avoids the bug)
qc.append(initializer, [0])  # append it to circuit (replace 'q' with the qubit index)

qc.h(0)
qc.cx(0, 1)

```

**Comment by cqc-alec** [comment]
Pytket doesn't have a built-in method for arbitrary state preparation. Your best bet may be to use the qiskit method for that, decompose the qiskit circuit to gates, and then convert to pytket using the pytket-qiskit extension module.
