### ISSUE TITLE
Can't open examples_backend.ipynb

### ISSUE THREAD

**Issue by hanschanhs** [CQCL/pytket#19]
After latest update the examples_backend.ipynb notebook fails to open. When launched with binder the following error appears:
**Unreadable Notebook: /home/jovyan/examples/backends_example.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')**

Have also tried copying the raw source code and running local, also fails to read.

**Comment by cqc-alec** [comment]
Thanks for the bug report. This should now be fixed.
