### ISSUE TITLE
Missing requirements in documentation

### ISSUE THREAD

**Issue by linda-anticoli** [CQCL/pytket#2]
When I tried to run `cirq_routing_example.ipynb`, I expected pytket to run the example correctly; instead I get an import error.

Upon inspection, I noticed this message:

`Library not loaded: /usr/local/opt/boost/lib/libboost_graph-mt.dylib`

I assumed that the solution then was that I did not have the Boost C++ libraries installed. I installed them using Homebrew and now the examples run fine. 

However, in the documentation Boost is not mentioned as a requirement, so I think that the installation instructions should be updated.

The same happens if you try to run `pyquil_example.ipynb` and `tket_benchmarking.ipynb`, since they require `pandas` and `quantum-groove` to be installed. 

After installing them via `pip` I was able to run all the code successfully.

### Environment

- Mac OS Mojave 10.14.3 (clean install)
- Python 3.7

### Potential solution

Add Boost C++ Libraries as an explicit requirement (for Mac OS only?). 

`pandas` and `quantum-groove` should be added in `requirements.txt`, or the documentation should mention that you need to install them to run the examples.

**Comment by ss2165** [comment]
Missing boost library for macos fixed in https://github.com/CQCL/pytket/releases/tag/v0.1.4

Notebooks will be updated to advise user to install dependencies in upcoming release
