### ISSUE TITLE
Issue with CircBox and converting Qiskit circuits that use 'to_instruction()'

### ISSUE THREAD

**Issue by oneTimePad** [CQCL/pytket#23]
**Analysis and Reproducing the Issue**
Consider the following code that runs a simple Qiskit circuit and converting it to a Pytket circuit. The circuit runs on IBM's AerBackend:

```
    from pytket.qiskit import qiskit_to_tk
    from pytket.backends.ibm import AerBackend
    from qiskit import QuantumCircuit, QuantumRegister

    boxed_circuit = QuantumCircuit(2)
    boxed_circuit.cx(0, 1)

    main_circuit = QuantumCircuit(2, 2)
    main_circuit.h(range(2))
    main_circuit.append(boxed_circuit.to_instruction(), range(2))
    main_circuit.measure(range(2),range(2))

    backend = AerBackend()
    tk = qiskit_to_tk(main_circuit)

    backend.compile_circuit(tk)
    res = backend.process_circuits([tk], n_shots=124)
    print(res[0].get_counts())
```

However, when the circuit is being validated against the GateSetPredicate an error occurs:
`
pytket.backends.backend_exceptions.CircuitNotValidError: Circuit with index 0 in submitted does not satisfy GateSetPredicate:{ Unitary1qBox Measure noop T CU1 Sdg S Y CZ Z CX X Tdg H SWAP Unitary2qBox U3 U2 U1 CCX } (try running backend.compile_circuit(circuit) first).
`

I narrowed down the issue to pytket/qiskit/qiskit_convert.py: line 118
`self.tkc.add_circbox(cbox, qubits + bits, **condition_kwargs)
`
this is because adding a Qiskit "Instruction" object maps to a Pytket "Circbox"

Since when the converted Pytket circuit is being verified: pytket/backends/backends.py: `Backend._check_all_circuits`

against the list of `required_predicates` : `[GateSetPredicate:{ Unitary1qBox Measure noop T CU1 Sdg S Y CZ Z CX X Tdg H SWAP Unitary2qBox U3 U2 U1 CCX }]`. "Circbox" is not present, which is why I think the above exception is being thrown.

In addition, I verified this by replacing the circuit above with one created just with Pytket:

```
    from pytket.circuit import Circuit, CircBox
    from pytket.qiskit import qiskit_to_tk
    from pytket.backends.ibm import AerBackend
    boxed_circuit = Circuit(2)

    boxed_circuit.CX(0,1)
    main_circuit = Circuit(2)
    circ_box = CircBox(boxed_circuit)
    main_circuit.H(0)

    main_circuit.add_circbox(circ_box, [0,1])

    main_circuit.measure_all()
    backend = AerBackend()
    backend.compile_circuit(main_circuit)
    result = backend.process_circuits([main_circuit], n_shots=124)
    print(backend.get_counts(result[0]))

```

which results in the same predicate error as with the first circuit. This is not only for the AerBackend, but also happens with IBMQBackend, which also has a predicate without "Circbox".

A temporary workaround I found was to have pytket/qiskit/qiskit_convert.py: line 118 use `Circuit.add_circuit` instead of using Circbox. Since this works:

```
    from pytket.circuit import Circuit, CircBox
    from pytket.qiskit import qiskit_to_tk
    from pytket.backends.ibm import AerBackend
    boxed_circuit = Circuit(2)
    boxed_circuit.CX(0,1)
    main_circuit = Circuit(2)

    main_circuit.H(0)
    main_circuit.add_circuit(boxed_circuit, [0,1])

    main_circuit.measure_all()
    backend = AerBackend()
    backend.compile_circuit(main_circuit)
    result = backend.process_circuits([main_circuit], n_shots=124)
    print(backend.get_counts(result[0]))
```

However, I assume this is not ideal.

**Comment by ss2165** [comment]
Thank you for reporting the issue and the code samples. Currenly, backends do not automatically decompose boxes, and boxes are not supported as valid gates in any backend's gateset. We will change this to do box decomposition in backend compilation passes when possible in the next release. In the mean time, as a workaround you could decompose the boxes yourself, by doing for example

```
from pytket.passes import DecomposeBoxes

DecomposeBoxes().apply(main_circuit)
backend.compile_circuit(main_circuit)
```

**Comment by oneTimePad** [comment]
This works. Thank you!

**Comment by willsimmons1465** [comment]
pytket 0.6.0 and associated updates to all of the extension modules (e.g. pytket-qiskit 0.6.0) have just been released, for which the default compiler passes provided with each backend will now automatically decompose all boxes. It should now be sufficient to just run `backend.compile_circuit(main_circuit)`. If you continue to have issues with the new version, let us know
