### ISSUE TITLE
`ImportError` with pytket>=1.20 and Python 3.11

### ISSUE THREAD

**Issue by robertodr** [CQCL/pytket#259]
Hello! I've been getting the following with the latest version of pytket when using Python 3.11:

```
ImportError: cannot import name '_TEMP_BIT_NAME' from 'pytket._tket.circuit' (/home/runner/work/aurora/aurora/.venv/lib/python3.11/site-packages/pytket/_tket/circuit.cpython-311-x86_64-linux-gnu.so)
```

**Comment by cqc-alec** [comment]
I assume from the error that you are using tket via an extension package, e.g. pytket-qiskit. If you update that to the latest version this should go away.

**Comment by robertodr** [comment]
Yes, found the issue in the TKET repo suggeting `pytket-qiskit` upgrade, right after opening this one. Sorry for the noise!
