### ISSUE TITLE
Manual build failing

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket#279]
See https://github.com/CQCL/pytket/actions/runs/7148621469/job/19469840915

Perhaps due to a quimb update?

**Comment by cqc-melf** [comment]
The manual build is failing again, not sure if this is the same as above or a new problem, see for example: https://github.com/CQCL/pytket-docs/pull/316

**Comment by cqc-alec** [comment]
> The manual build is failing again, not sure if this is the same as above or a new problem, see for example: #316

This is the same issue, caused by the update to scipy 1.13: https://github.com/CQCL/tket/pull/1323 will pin scipy to 1.12 in pytket to work around this, and @CalMacCQ is working on a similar fix in pytket-docs so that it works with current pytket.
