### ISSUE TITLE
No mapping for Qiskit multi-controlled gates during circuit conversion to Pytket

### ISSUE THREAD

**Issue by oneTimePad** [CQCL/pytket#28]
In pytket version 0.6.0, there seems to be no mapping for Qiskit's multi-controlled gates. For example, the multi-controlled X: `QuantumCircuit.mct` and `QuantumCircuit.mcx`.

 Internally, in Qiskit's `QuantumCircuit`, these map to one of the different implementations like `MCXVChain` and `MCXGrayCode` only when the number of control qubits is greater than two. 

Locally, for the X gate, I resolved this by mapping all of these variants to pytket's `OpType.CnX` for now.

**Comment by cqc-alec** [comment]
Thank you for the report. Indeed, support for multi-controlled X gates is missing from the qiskit converters. We will aim to fix this in a patch release soon.

**Comment by oneTimePad** [comment]
Thank you!

**Comment by cqc-alec** [comment]
We have just released pytket-qiskit 0.6.1, which should fix this issue. (Note that we have also just released core pytket 0.6.1 and recommend upgrading that at the same time.)
