### ISSUE TITLE
RuntimeError when mapping to Aspen

### ISSUE THREAD

**Issue by akissinger** [CQCL/pytket#3]
I get a mysterious "RuntimeError: 4" error when I try to map a certain 16-qubit CNOT circuit to the Rigetti 16Q-Aspen architecture. This seems to only happen for some circuits, so I suspect its some sort of funny edge case.

I've attached a minimal example, with the crashing circuit (Original0.qasm) and a very similar working circuit (Original1.qasm).

[tket-error.zip](https://github.com/CQCL/pytket/files/3025300/tket-error.zip)

**Comment by ss2165** [comment]
Fixed in v0.1.4
