### ISSUE TITLE
No mapping for custom Qiskit 'qiskit.circuit.Gate' objects

### ISSUE THREAD

**Issue by oneTimePad** [CQCL/pytket#31]
There doesn't seem to be any mapping in `qiskit_convert.py` for custom gates constructed in Qiskit via the `QuantumCircuit.to_gate` method. I resolved this locally for now by adding a mapping from Qiskit `qiskit.circuit.Gate` to pytket's custom gate via `pytket.circuit.CustomGateDef`, which seems to work.

**Comment by ss2165** [comment]
Hi @oneTimePad, apologies for the slow pick up on this. Thank you for the suggestion, I've implemented this internally now and we will include it with the next release of pytket-qiskit and pytket

**Comment by ss2165** [comment]
pytket-qiskit 0.7.0 now includes this.
