### ISSUE TITLE
New pip dependency resolver is wreaking havok

### ISSUE THREAD

**Issue by mpharrigan** [CQCL/pytket#32]
I'm trying to install cirq 0.9.1 and pytket, which should work in theory. The details of my tribulations are here: https://github.com/quantumlib/ReCirq/issues/104

In summary: since the latest version of pytket wants cirq ~= 0.8.0 and I specifically ask for cirq 0.9.1, the dependency resolver goes hunting for something that will work and it sees that pytket-cirq 0.3 has a specification that is looser: it requires cirq ~= 0.6 (note the lack of third decimal). It mixes-and-matches pytket-cirq 0.3 with pytket 0.6.1 which results in disaster.

Suggestions:
 - looser pin to cirq. We'll try not to break anything :)
 - the pytket <--> pytket-cirq pinning should be stronger 
 - If you don't want to loosen the pin to cirq, please allow cirq 0.9.x which works fine

**Comment by cqc-alec** [comment]
Hi Matthew,
Thanks for reporting this.
The easiest solution is probably for us to do a hotfix release of `pytket-cirq`, changing the requirement to `>= 0.9`.
I'll report back here when that's done.

**Comment by cqc-alec** [comment]
Released pytket-cirq 0.5.1 which should fix this issue.
