### ISSUE TITLE
pytket-pyzx should convert phases to Fraction

### ISSUE THREAD

**Issue by jvdwetering** [CQCL/pytket#34]
The method `pytket.pyzx.tk_to_pyzx` converts phases in gates like Z and X rotations to floating points, instead of to `Fraction` instances. This is a problem for instance for `V` gates, which get converted to `XPhase(0.5)` gates, while it should be converted to `XPhase(Fraction(1,2))`. I'm actually kind of surprised PyZX didn't raise an exception for this.

**Comment by cqc-alec** [comment]
Will be fixed in next release.

**Comment by ss2165** [comment]
Fixed in pytket-pyzx 0.6.0
