### ISSUE TITLE
Unable to get started

### ISSUE THREAD

**Issue by c-poole** [CQCL/pytket#36]
I have recently tried to install pytket on a Windows 10 Enterprise LTSC machine and am unable to use the package from the get-go. I am using Python 3.7.9 and use the command pip install pytket==0.6.1. The installation works but when I load up a python console and try to import pytket, it fails with the following message:
```
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\QC\Envs\pyqt\lib\site-packages\pytket\__init__.py", line 18, in <module>
    from pytket.circuit import (
  File "C:\Users\QC\Envs\pyqt\lib\site-packages\pytket\circuit\__init__.py", line 17, in <module>
    from pytket._tket.pauli import Pauli
ImportError: DLL load failed: The specified module could not be found.
```
I have looked in the _tket folder on this machine and the files that need to be there do appear to be there as they match the filenames for an install of pytket I have on another machine with the same version of python and pytket that works. The computer with the functioning installation has just Enterprise instead of Enterprise LTSC. I've gone as far as making a requirements file out of a pip freeze from a functioning virtual environment on the functioning machine and using that to set up an environment on the failing machine for the project I'm working on as well as only having pytket installed. Failure happens in each case.

EDIT: Problem also seems to exist on Python 3.8.2 for the same machine.

**Comment by ss2165** [comment]
Thank you for the report and trying what you have already, I am not sure what is happening but it may well be that our windows builds are not compatible with LTSC as a platform. My only suggestion for now is, if possible could you try installing with a a conda distribution of python, rather than a system one?

**Comment by c-poole** [comment]
Same issue I'm afraid.

**Comment by ss2165** [comment]
The LTSC versions of Windows are designed to not change for 10 years, and are intended for very static, special purpose systems (more [here](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/ltsc-what-is-it-and-when-should-it-be-used/ba-p/293181)). In that sense I suppose it is not that surprising something breaks there, but pip should not have installed it if that were the case. Unfortunately I think the best we can do is add a warning to the installation docs that LTSC may not work. Are you able to try something like a virtual machine or a docker container on that system?
