### ISSUE TITLE
Math display errors in circuit_generation_example.ipynb

### ISSUE THREAD

**Issue by stfnmangini** [CQCL/pytket#46]
Hi 👋 

I was having a look at the notebook `circuit_generation_example.ipynb` (https://github.com/CQCL/pytket/blob/master/examples/circuit_generation_example.ipynb) and I found two minor math display errors in two equations. In details: 

1. line 357: there is a `\\frac12` instead of `\\frac{1}{2}`, which outputs an erroneous Rz rotation with a "-12/i" instead of "-1/2 * i";
2. line 579: same as before, `\\frac12` instead of `\\frac{1}{2}`, which creates some problem with the brackets in the equation.

Didn't know if opening a PR would be the best thing to do in this case for you, so I opened an issue. Hope that's fine 😅 

🙂

**Comment by cqc-alec** [comment]
Hi, thanks for pointing this out! It seems that although `\frac12` works in LaTeX as parsed by TeX, it doesn't render as intended in the notebook and we have to put in the braces...

**Comment by cqc-alec** [comment]
Fixed!

**Comment by stfnmangini** [comment]
Glad to help :D
Actually, didn't know Tex parsed `\frac12` correctly. I've wasted so many braces then! 
Good to know, thanks! :)
