### ISSUE TITLE
can  not find dll

### ISSUE THREAD

**Issue by yinxx** [CQCL/pytket#98]
import pytket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\python\python37\lib\site-packages\pytket\__init__.py", line 11, in <module>
    from pytket.circuit import (  # type: ignore
  File "E:\python\python37\lib\site-packages\pytket\circuit\__init__.py", line 14, in <module>
    from pytket._tket.circuit import *  # type: ignore
ImportError: DLL load failed: 找不到指定的模块。

**Comment by cqc-alec** [comment]
Hi, thanks for the report.
Could you please state the version of pytket you have installed (the output of `pip show pytket`), and also details of the system you are running on (OS version, architecture)?

**Comment by yinxx** [comment]
pip show pytket
Name: pytket
Version: 0.13.0
Summary: Python module for interfacing with the CQC tket library of quantum software
Home-page: https://cqcl.github.io/pytket
Author: Seyon Sivarajah
Author-email: seyon.sivarajah@cambridgequantum.com
License: CQC Software Licence
Location: e:\python\python37\lib\site-packages
Requires: numpy, types-pkg-resources, types-Jinja2, graphviz, typing-extensions, networkx, jinja2, scipy, lark-parser, sympy
Required-by:

**Comment by yinxx** [comment]
os : windows 7

**Comment by cqc-alec** [comment]
What about the architecture? Can you try
```
python -c "import platform; print(platform.architecture(), platform.uname())"
```
Note that only 64-bit is supported.

**Comment by yinxx** [comment]
python -c "import platform; print(platform.architecture(), platform.uname())"
('64bit', 'WindowsPE') uname_result(system='Windows', node='admin-PC', release='7', version='6.1.7601', machine='AMD64', processor='Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')

**Comment by cqc-alec** [comment]
Thanks. I am not sure what the problem is; however we have found that Windows installations can break for certain versions. Windows 7 is not an officially supported OS (we test on Windows 10), and we are unable to reproduce the issue as we do not have access to a Windows 7 machine.

Sorry I can't be of more help. Are you able to switch to a different OS (Linux, MacOS >= 10.14 or Windows 10) to run pytket?
