### ISSUE TITLE
Expand NumPy version compatibility

### ISSUE THREAD

**Issue by nonnymouse6432** [CQCL/pytket#99]
pytket currently requires numpy~=1.20. Unfortunately TensorFlow is stuck at numpy<1.20, and looks as though it will be for a while (Google and TensorFlow are very large beasts to move), so pytket and TensorFlow are incompatible for the foreseeable future.

Is there any chance pytket could relax its numpy requirement to >=1.19,<1.21?

**Comment by cqc-alec** [comment]
Hi, thanks for pointing this out. I don't think pytket relies on any features of numpy 1.20, though we also need to check all the pytket extensions and their dependencies. We will test this, and if all is OK can relax the requirement.

**Comment by cqc-alec** [comment]
Hi, thanks for pointing this out. I don't think pytket relies on any features of numpy 1.20, though we also need to check all the pytket extensions and their dependencies. We will test this, and if all is OK can relax the requirement.

**Comment by cqc-alec** [comment]
This will be changed in pytket 0.14 to allow numpy 1.19.

**Comment by cqc-alec** [comment]
Fixed in pytket 0.14.
